name: GeoDiffuser
channels:
  - xformers
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - anaconda
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - blas=1.0=mkl
  - blosc=1.21.3=h6a678d5_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py310h6a678d5_7
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.2.2=hbcca054_0
  - cffi=1.16.0=py310h5eee18b_0
  - cfitsio=3.470=h5893167_7
  - charls=2.2.0=h2531618_0
  - click=8.1.7=py310h06a4308_0
  - cloudpickle=2.2.1=py310h06a4308_0
  - cryptography=41.0.7=py310hdda0065_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.3.101=0
  - cuda-runtime=12.1.0=0
  - cytoolz=0.12.2=py310h5eee18b_0
  - dask-core=2023.11.0=py310h06a4308_0
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.2.10=h9c3ff4c_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.1=hef1e5e3_0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - icu=58.2=hf484d3e_1000
  - idna=3.4=py310h06a4308_0
  - imagecodecs=2023.1.23=py310hc4b7b5f_0
  - imageio=2.31.4=py310h06a4308_0
  - importlib-metadata=7.0.1=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.2=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jxrlib=1.1=h7b6447c_2
  - kaleido-core=0.2.1=h3644ca4_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lazy_loader=0.3=py310h06a4308_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libavif=0.11.1=h5eee18b_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.107=0
  - libcurl=8.5.0=h251f7ec_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxml2=2.9.14=h74e7548_0
  - libzopfli=1.0.3=he6710b0_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - locket=1.0.0=py310h06a4308_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py310h5eee18b_0
  - mathjax=2.7.7=ha770c72_3
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py310h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numpy=1.26.3=py310h5f9d8c6_0
  - numpy-base=1.26.3=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_0
  - partd=1.4.1=py310h06a4308_0
  - pillow=10.0.1=py310ha6cbd5a_0
  - pip=23.3.1=py310h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - python-kaleido=0.2.1=pyhd8ed1ab_0
  - pytorch=2.1.0=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pywavelets=1.5.0=py310ha9d4c09_0
  - pyyaml=6.0.1=py310h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py310h06a4308_0
  - scikit-image=0.20.0=py310h6a678d5_0
  - setuptools=68.2.2=py310h06a4308_0
  - snappy=1.1.10=h6a678d5_1
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.12=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=8.2.2=py310h06a4308_0
  - tifffile=2023.4.12=py310h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.12.0=py310h06a4308_0
  - torchtriton=2.1.0=py310
  - torchvision=0.16.0=py310_cu121
  - typing-extensions=4.9.0=py310h06a4308_1
  - typing_extensions=4.9.0=py310h06a4308_1
  - wheel=0.41.2=py310h06a4308_0
  - xformers=0.0.22.post7=py310_cu12.1.0_pyt2.1.0
  - xz=5.4.5=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zfp=1.0.0=h6a678d5_0
  - zipp=3.17.0=py310h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - accelerate==0.26.1
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - altair==5.2.0
      - annotated-types==0.6.0
      - anyio==4.2.0
      - asttokens==2.4.1
      - async-timeout==5.0.1
      - attrs==23.2.0
      - certifi==2024.2.2
      - charset-normalizer==2.0.4
      - colorama==0.4.6
      - contourpy==1.2.0
      - cupy-cuda12x==13.0.0
      - cycler==0.12.1
      - dataclasses==0.6
      - decorator==4.4.2
      - diffusers==0.25.1
      - einops==0.7.0
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastapi==0.109.0
      - fastrlock==0.8.2
      - ffmpy==0.3.1
      - fonttools==4.47.2
      - frozenlist==1.5.0
      - fsspec==2023.12.2
      - ftfy==6.1.3
      - fvcore==0.1.5.post20221221
      - gradio==4.44.1
      - gradio-client==1.3.0
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - huggingface-hub==0.20.3
      - imageio-ffmpeg==0.4.9
      - importlib-resources==6.1.1
      - iopath==0.1.9
      - ipython==8.20.0
      - jedi==0.19.1
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - lightning==2.2.0.post0
      - lightning-utilities==0.10.1
      - lpips==0.1.4
      - markdown-it-py==3.0.0
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - memory-efficient-attention-pytorch==0.1.6
      - moviepy==1.0.3
      - multidict==6.1.0
      - openai-clip==1.0.1
      - opencv-contrib-python==4.9.0.80
      - opencv-python==4.9.0.80
      - orjson==3.9.12
      - packaging==23.2
      - pandas==2.2.0
      - parso==0.8.3
      - pexpect==4.9.0
      - plotly==5.19.0
      - portalocker==1.4.0
      - proglog==0.1.9
      - prompt-toolkit==3.0.43
      - propcache==0.2.1
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pydub==0.25.1
      - pygments==2.17.2
      - pyparsing==3.1.1
      - pyrealsense2==2.54.2.5684
      - python-dateutil==2.8.2
      - python-multipart==0.0.9
      - pytorch-lightning==2.1.3
      - pytz==2023.3.post1
      - referencing==0.32.1
      - regex==2023.12.25
      - rich==13.7.0
      - rpds-py==0.17.1
      - ruff==0.6.2
      - safehttpx==0.1.6
      - safetensors==0.4.1
      - scipy==1.12.0
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - six==1.16.0
      - sniffio==1.3.0
      - stack-data==0.6.3
      - starlette==0.35.1
      - tabulate==0.9.0
      - termcolor==2.4.0
      - timm==0.9.12
      - tokenizers==0.15.1
      - tomlkit==0.12.0
      - torchmetrics==1.2.1
      - tqdm==4.66.1
      - traitlets==5.14.1
      - transformers==4.37.0
      - typer==0.12.5
      - tzdata==2023.4
      - urllib3==2.2.2
      - uvicorn==0.27.0
      - wcwidth==0.2.13
      - websockets==11.0.3
      - yacs==0.1.8
      - yarl==1.18.3
prefix: /home/ssrinath/anaconda3/envs/GeoDiffuser
